### ISSUE TITLE
[JS] ToDo List

### ISSUE THREAD

**Issue by foxprogs** [tt-dev-23/Yuriy2437_Practice#13]
## Задача - создать todo list
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/9e868625-6ff0-4ff3-b955-6710f907d772)

- [ ] Будем делать в первую очередь для мобильных устройств, по этому первая задача - сверстать согласно дизайну, но с некоторыми изменениями.
- В заголовке будет название сайта (дать любое)
- Кнопка добавить - фиксированная всегда внизу
- Круг, для того чтобы отмечать выполненым - сделаем слева, до текста
- Справа сделаем кнопку три точки, по нажатию на которую можно будет выбрать или редактировать задачу или удалить

- [ ] При нажатии + у нас вверху добавляется строка, новая задача. Сразу становится активным поле где надо написать название задачи. Все задачи мы сохраняем в localStorage браузера
- [ ] Двойной тап или двойной клик по задаче переводит ее в режим редактирования, можно поменять текст. Если кликать по правой части то должно всплывать меню с двумя пунктами карандаш и корзинка, если кликать справа то можно сделать задачу выполненной или отменить выполнение
- [ ] В меню удаление убирает задачу, если нажать карандаш - то можно редактировать текст задачи
- [ ] Сделать поддержку перетаскивания, чтобы можно было самому менять порядок в списке
...

Все вопросы по самой задаче можно обсудить тут. Так же со временем будем добавлять возможно какой-то функционал еще
